[build]
  command = "npm ci && npm run build"
  publish = "dist"
  ignore = "/bin/false"

[build.environment]
  NODE_VERSION = "22.13.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
